### ISSUE TITLE
Project2-适配说明标题有误

### ISSUE THREAD

**Issue by King-ty** [fung-hwang/CS110L-2020spr#1]
貌似是忘记更改Project1的题目，其实无伤大雅，望有空随手更正~

![image](https://user-images.githubusercontent.com/56447783/205856749-950fdf14-0bab-45fb-8658-1970a223521b.png)

BTW：非常感谢您的适配分享！他对我的帮助非常大！

**Comment by fung-hwang** [comment]
谢谢提醒，已修改。
